### ISSUE TITLE
How to run all tests?

### ISSUE THREAD

**Issue by tizmagik** [jesseskinner/webpack-mocha-demo#1]
Thanks for putting together this repo (and your YouTube video), this is very helpful.

Do you know if there's any way to specify a full directory of tests to run through? For example, I have a `./test/` directory with all my mocha tests (including a `__bootstrap.js` which instantiates some common global modules and variables needed for the tests). Is there any way to run the CLI or webserver tests recursively?

I was hoping for something like:
`webpack-dev-server mocha\!./test/**/*.js --output-file testBundle.js --config webpack.client.js`

But I guess that doesn't make sense since there's only one `output-file` being specified. Maybe I need to use `--content-base` and point it at the `./test/` directory or something? I've tried a bunch of things with no luck. Any ideas?

**Comment by jesseskinner** [comment]
My guess is that you could have a test/index.js file as an entry that requires all your test files and therefore makes testBundle.js make sense? Or you can have multiple entries, one for each test, if you prefer to set it up that way. Let me know if that helps (or if it doesn't work, since I'm just guessing here).
